Add diagnostics
IDAES/idaes-ui pull request #34
Opened 2023-10-24 21:39 UTC by CopyDemon

Fixes
Fix the UI panel layout, remove the variables panel, and change that panel to a multi-task panel. Now it can display diagnostics.

Proposed changes:
Create a diagnostics panel to display diagnostics.

Notice
Now the diagnostics only run on fixed JSON data, later when the API is up to date, will rewrite some functions in diagnostics.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

2023-10-30 17:22 UTC, dangunter reviewed
I assume this will be incorporated in a future PR that uses real/live diagnostic info. Should we move this PR back to draft?

2023-10-30 17:33 UTC, CopyDemon commented
@dangunter you are right, I just turned this PR into draft, and start to work on serve the new UI with FastAPI.

2024-01-18 19:53 UTC, lbianchi-lbl commented
The current plan is to merge #43 first and then this one (which is also expected to resolve the current CI failures).

2024-02-13 22:31 UTC, lbianchi-lbl commented on idaes_ui/fv/fastAPI_route/api_post_diagnostics_runner.py
> +                    dt.display_potential_evaluation_errors(stream=output_stream)
```suggestion
            func = getattr(dt, request.function_name, None)
            if func is None:
                ...
                # TODO handle error
            func(stream=output_stream)
```

2024-04-04 15:55 UTC, dangunter commented
@CopyDemon Could you rebase this on main? I see some merge conflicts there

2024-04-04 17:42 UTC, CopyDemon commented
> Could you rebase this on main? I see some merge conflicts there

Working on it now

2024-04-24 16:46 UTC, dangunter commented
@CopyDemon is this ready to review now?

2024-04-29 18:49 UTC, CopyDemon commented
@dangunter This ticket is ready for review now:
1. Fixed the error that occurred when dragging the diagnostics panel.
2. Added a utility to show user notifications when refreshing, saving, and loading/refreshing diagnostics.
3. Added a utility to reset the layout.

2024-05-05 15:01 UTC, dangunter commented
First question: why is the "dist" directory being checked into git? Aren't all those files generated by building the package?

2024-05-05 15:03 UTC, dangunter commented on IDAES-UI/dist/css/ag-grid.css
Remove dist/ directory from git

2024-05-05 15:14 UTC, dangunter commented on IDAES-UI/src/components/mosaic/mosic.tsx
This file needs to be (a) renamed: what does "mosaic" mean? We shouldn't be naming our code for the packages they are using; (b) commented: what does it do, why, who is calling it, what does it call, which are the major functions and what do they do?

2024-05-05 18:17 UTC, dangunter commented
@CopyDemon I think we need to reduce the number of small files in deeply nested directories. See https://github.com/dangunter/idaes-ui/tree/add-diagnostics/IDAES-UI for a start on this, moving the entire tree under `src/components/header_components` to the top of `src` with 3 pairs of files
* Header.tsx, Header.module.css
* HeaderButtons.tsx, HeaderButtons.module.css
* DiagnosticsToggle.tsx, DiagnosticsToggle.module.css

This replaces 14 files with 4 levels of hierarchy (including `components/`) with 6 files and 1 level of hierarchy, yet retains flexibility and is easier to understand and maintain.

2024-05-09 18:26 UTC, dangunter requested changes
See prev comment

2024-05-13 15:34 UTC, dangunter commented
From running the tool, there is another thing that needs to be fixed.
In the "Diagnostics Logs" tab of the lower panel, when you run a diagnostic function, it does not provide a horizontal scroll even when the text is wider than the screen. See screenshot below.

![image](https://github.com/IDAES/idaes-ui/assets/420923/a0938ef8-c5b2-4fe8-b244-1283ef490de0)

2024-06-13 18:19 UTC, merged